
#ifndef LINKID_H
#define LINKID_H


enum class LinkID : uint8_t {
   FIRST_COLUMN_LINK = 0,
   FIRST_TOWER_LINK = 50,
   FIRST_ACE_LINK = 54,
   FIRST_THRONE_LINK = 58,
   LINK_COUNT = 62,
   NO_LINK = LINK_COUNT,
   LINK_COUNT_INCLUDING_NO_LINK = NO_LINK + 1
};


#endif
